#
# Ken Iovino
#
# Copyright (c) 2011-2014, DIVUPS, LLC.
#

source "https://supermarket.getchef.com"

metadata

cookbook "apt"
cookbook "build-essential"
cookbook "git"
cookbook "apache2"
cookbook 'mysql', '~> 5.6.3'
cookbook "php"
cookbook "composer"
cookbook "nodejs"
